# Generated by Django 4.2.2 on 2023-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_de_temas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='complement',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='ddd',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='date',
            new_name='dataFesta',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='end_hours',
            new_name='horarioInicio',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='start_hours',
            new_name='horarioTermino',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='color',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='price',
            new_name='valorAluguel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='address',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
