# Generated by Django 4.2.2 on 2023-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_de_temas', '0002_rename_city_address_bairro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='bairro',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='complemento',
            new_name='complement',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='cidade',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='logradouro',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='cliente',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='area',
            new_name='ddd',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='dataFesta',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='horarioInicio',
            new_name='end_hours',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='horarioTermino',
            new_name='start_hours',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='cor',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='valorAluguel',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
