# Generated by Django 4.2.2 on 2023-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_de_temas', '0003_rename_bairro_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
